[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments]
production.PORT = "3000" 